language: php

php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

os:
    - linux
    - osx

matrix:
    allow_failures:
      - os: osx

notifications:
    email: dev@anime-db.org

before_script:
    - composer self-update
    - composer --version
    - composer install --dev --prefer-dist

script:
    - phpunit --verbose --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
