language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

notifications:
    email: deploy@anime-db.org

before_script:
    - composer install --dev --prefer-dist

script:
    - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
    - vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml
    - vendor/bin/coveralls -v -c .coveralls.yml
