language: php

notifications:
    email: deploy@anime-db.org

matrix:
    fast_finish: true
    include:
        - php: 7.1
        - php: 7.0
        - php: 5.6
        - php: 5.5
        - php: 5.4
        - php: hhvm
          sudo: required
          dist: trusty
          group: edge

before_install:
    - if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then echo 'xdebug.enable = on' >> /etc/hhvm/php.ini; fi
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

before_script:
    - composer install --dev --prefer-dist

script:
    - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
    - vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml
    - vendor/bin/coveralls -v -c .coveralls.yml
