parameters:
    anime_db.world_art.host: 'http://www.world-art.ru'
    anime_db.world_art.user_agent: 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.2 Safari/537.36'
