services:
    anime_db.world_art.browser:
        class: AnimeDb\Bundle\WorldArtBrowserBundle\Service\Browser
        arguments:
            - "@anime_db.world_art.browser.client"
            - "@anime_db.world_art.browser.tidy"
            - ~
            - ~

    anime_db.world_art.browser.client:
        class: Guzzle\Http\Client
        arguments: [ "%anime_db.world_art.host%" ]
        public: false

    anime_db.world_art.browser.tidy:
        class: tidy
        public: false
